version: '3.8'

services:
  db_mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS:-main}"
      MYSQL_DATABASE: ${DB_NAME:-main}
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER:-main}"
      MYSQL_PASSWORD: "${DB_PASS:-main}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

volumes:
  db_mysql_data: