version: '3.8'

services:
  db_mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS:-main}"
      MYSQL_DATABASE: ${DB_NAME:-main}
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER:-main}"
      MYSQL_PASSWORD: "${DB_PASS:-main}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

  backend_nest:
    image: node:18.16.0
    working_dir: /usr/src/app
    build: ./backend_nest/docker
    command: bash -c "yarn install && yarn start:dev"
    ports:
      - ${BACKEND_PORT:-3000}:3000
    volumes:
      - ./backend_nest:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db_mysql

volumes:
  db_mysql_data: